---
- name: deploy lamp stack
  hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/vagrant/lamp.sh
        dest: /home/vagrant/lamp.sh
        owner: root
        group: root
        mode: '0755'

    - name: install lamp stack and laravel
      script: /home/vagrant/lamp.sh
    
    - name: Add cron job for uptime check
      cron:
        name: "Check server Uptime check"
        minute: "0"
        hour: "0"
         job: "uptime >> /var/log/server_uptime.log"
      
     
